import 'package:flutter/material.dart';
import 'package:sportzenzehra/core/theme/app_colors.dart';

class RulesView extends StatelessWidget {
  const RulesView({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Text(
        '''
SAYGIDEĞER ÜYELERİMİZ;

Yönetim Kurulumuzun aldığı karar ile Defi Kurulu,
SEYHUN SEYHAN, YUSUF COPUR ve ATDSK YÖNETİM KURULU'NDAN oluşmaktadır. 
2024 Yılı Defi Ligi'nde görevlerini sürdürecek olan Defi Kurulu Üyeleri, 
ATDSK Yönetim Kurulu'na yardımcı olmak amacıyla kulübümüz üyelerinden 
oluşturulmuş olup, çalışmalarını yürütmektedir. 

ATDSK 2024 DEFİ LİGİ'ne katılan üyelerimize başarı dilerken, 
Yönetimimize, Defi Ligi'ne ve Defi Kurulu'na vereceğiniz destek ve 
göstereceğiniz anlayışlarınızdan dolayı teşekkür ederiz.

ATDSK Yönetim Kurulu ATDSK 2024 DEFİ KURALLARI ;

1.1. 2024 DEFİ LİGİ 15.03.2024 İTİBARİYLE BAŞLAYACAKTIR.

1.2. MAÇ TEKLİFLERİ SERVE 24 ÜZERİNDEN OYUNCUYA YAPILIR, 
BUNUN İÇİN OYUNCUNUN ARANMASINA GEREK YOKTUR.

1.3. DEFİ LİGİNDE OYUNCULARIN 2024 YILI SIRALAMALARI 
KENDİ İÇLERİNDE YAPILACAK KURA ÇEKİMİ İLE BELİRLENİP, 
YENİ SIRA OLUŞTURULACAKTIR.

2. MAÇLAR 3 SET ÜZERİNDEN OYNANIR, SETLERİN 1-1 OLMASI DURUMUNDA 
FİNAL SETİ 10 SAYILIK SÜPER TIE-BREAK OYNANIR.

3. HER OYUNCU DEFİ PİRAMİDİNDE SOLUNDAKİ OYUNCUDAN 
ÜST SIRADAKİ KOMŞUSUNA KADAR (SOL ÜST KOMŞUSU DAHİL) 
OLAN OYUNCULARA MAÇ TEKLİFİ YAPABİLİR. 
İLK 5 OYUNCU DA BU KURALA TABİDİR.

4.1. MAÇ SKORU KAZANAN OYUNCU TARAFINDAN GİRİLECEKTİR. 
MAÇ SONUÇLARINA GÖRE PİRAMİTTEKİ SIRALAMA SERVE24 ÜZERİNDE 
OTOMATİK OLARAK GÜNCELLENİR. 

4.2. MAÇ SKORU YANLIŞ GİRİLDİĞİNDE DEFİ KURULU BİLGİLENDİRİLECEKTİR. 
BU YAPILMADIĞI TAKDİRDE SKORUN BİLEREK YANLIŞ GİRİLDİĞİ DEĞERLENDİRİLİR 
VE OYUNCU ESKİ SIRALARINA ALINIR. 
İLAVETEN 5 SIRA KAYBI CEZASI UYGULANIR.

5.1. MAÇ TEKLİFİ ALAN OYUNCU, TEKLİFİ YAPAN OYUNCUYA 
BİR DEFA RED CEVABI VERME HAKKINA SAHİPTİR. 
RED CEVABI VEREN OYUNCUYA İKİNCİ TEKLİF EN ERKEN 3 GÜN SONRA 
VEYA ALTTAN YA DA ÜSTTEN MAÇ YAPTIKTAN SONRA YAPILABİLİR.

5.2. OYUNCU, DAHA ÖNCE RED VERDİĞİ AYNI OYUNCUDAN TEKLİF ALDIĞINDA 
İKİNCİ KEZ RED VEREMEZ. TEKLİF ALAN OYUNCU, İKİNCİ KEZ RED VERDİĞİ 
TAKDİRDE WALKOVER OLUR, MAÇI KAYBEDER.

5.3. HERHANGİ BİR NEDENLE MAÇA ÇIKMAYIP WALKOVER OLAN OYUNCU 
SİSTEMDE İNAKTİF OLUR. 7 GÜN CEZA ALIR. 
CEZA ALAN OYUNCU 7 GÜN SÜRESİNCE ÜSTE MAÇ TEKLİFİ YAPAMAZ. 
ANCAK ALTTAN GELEN TEKLİFLERE AÇIKTIR. 
CEZALI DURUMU NEDENİYLE CEZA SÜRESİNCE ALTTAN TEKLİFLERE DE RED VEREMEZ.

5.4. DEFİ MAÇI SONRASI SKOR GİRİLMEDİĞİ TAKDİRDE 
HER İKİ OYUNCUYA DA 5 ER SIRA KAYBI UYGULANIR.

5.5. BİR OYUNCU, HER AY İÇİN BİR DEFA RED VERME HAKKINA SAHİPTİR. 
AY İÇERİSİNDE HİÇ RED HAKKINI KULLANMAYAN OYUNCUNUN RED HAKKI SİLİNİR, 
KULLANMADIĞI RED HAKKI MÜTEAKİP AYA EKLENMEZ.

6.1. AYNI OYUNCUDAN İKİNCİ KEZ DEFİ TEKLİFİNE, TEKLİF İÇİN 
BELİRLENEN SÜRE İÇERİSİNDE DÖNÜŞ YAPMAYAN YA DA YAYINLANAN 
- ANLAŞILAN SAATTE SEBEP NE OLURSA OLSUN KORTA ÇIKMAYAN 
OYUNCU WALKOVER İLE MAÇI KAYBEDER. 

TARAFLAR (YAĞMUR VE TTF TURNUVALARI, KULÜP İÇİ TURNUVA HARİÇ) 
ARALARINDA ANLAŞARAK MAÇI ERTELEYEMEZLER, İPTAL EDEMEZLER.
          ''',
        style: theme.textTheme.bodySmall?.copyWith(
          fontSize: 13,
          fontWeight: FontWeight.w500,
          color: AppColors.black90,
        ),
      ),
    );
  }
}
